config/routes.rb
Rails.application.routes.draw do

	root :to => 'books#top'
	resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, presence: true
	validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def top
  end

  def index
  	@books = Book.all
  	@book = Book.new
  end

  def create
  	@book = Book.new(book_params)
    if @book.save
       flash[:notice] = "Book was successfully created."
  	   redirect_to book_path(@book.id)
  	else
  		@books = Book.all
  		render :index
  	end
  end

  def show
  	@book = Book.find(params[:id])
  end

  def new
  end

  def edit
  	@book = Book.find(params[:id])
  end

  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  	   flash[:notice] = "Book was successfully updated."
  	   redirect_to book_path(@book.id)
  	else
  		render :edit
  	end
  end

  def destroy
  	book = Book.find(params[:id])
  	book.destroy
  	redirect_to books_path
  end


  private

  def book_params
  	params.require(:book).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<body>
	<h1>Editing Book</h1>
	<%= form_for(@book) do |f| %>

		<% if @book.errors.any? %>
  		<div id="error_explanation" class="alert alert-danger">
    		<ul>
      		<% @book.errors.full_messages.each do |message| %>
        	<li><%= message %></li>
      		<% end %>
    		</ul>
  		</div>
		<% end %>


	<%= f.label :title, 'Title' %><br>
	<%= f.text_field :title %><br>

	<%= f.label :body, 'Body' %><br>
	<%= f.text_area :body %><br>

	<%= f.submit 'Update Book' %>

	<% end %>

	<%= link_to "Show", book_path(@book.id) %>
	|
	<%= link_to "Back", books_path %>
</body>

app/views/books/index.html.erb
<body>
	<h1>Books</h1>
	<table>
		<tr>
			<th width="30%">Title</th>
			<th width="50%">Body</th>
			<th Width="20%" colspan="3"></th>
		</tr>
		<% @books.each do |book| %>
		<tr>
			<td><%= book.title %></td>
			<td><%= book.body %></td>
			<td><%= link_to "Show", book_path(book.id) %>
			</td>
			<td><%= link_to "Edit", edit_book_path(book.id) %>
			</td>
			<td><%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "Are you sure?"%>
			</td>
		</tr>
		<% end %>
	</table>

	<h2>New book</h2>
	<%= form_for(@book) do |f| %>
		<% if @book.errors.any? %>
  		<div id="error_explanation" class="alert alert-danger">
    	<ul>
      		<% @book.errors.full_messages.each do |message| %>
        	<li><%= message %></li>
      		<% end %>
   		 </ul>
  		</div>
		<% end %>

	<%= f.label :title, 'Title' %><br>
	<%= f.text_field :title %><br>

	<%= f.label :body, 'Body' %><br>
	<%= f.text_area :body %><br>

	<%= f.submit 'Create Book' %>

	<% end %>
</body>

app/views/books/show.html.erb
<body>
	<P class=success><%= flash[:notice] %></P>
	<p>
		<strong>Title:</strong>
		<%= @book.title %>
	</p>

	<p>
		<strong>Body:</strong>
		<%= @book.body %>
	</p>

	<%= link_to "Edit", edit_book_path %>
	|
	<%= link_to "Back", books_path %>
</body>

app/views/books/top.html.erb
<body>
	<h1>
		ようこそ <strong>Bookers</strong> へ！
	</h1>
	<p>
		<strong>Bookers</strong> では、さまざまな書籍に関するあなたの意見や
	</p>
	<p>印象を共有し交換することができます</p>
	<%= link_to "start", books_path, class: "start" %>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>